-- MySQL Script generated by MySQL Workbench
-- Sun Feb 25 18:25:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema auction_platform
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auction_platform
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auction_platform` DEFAULT CHARACTER SET utf8 ;
USE `auction_platform` ;

-- -----------------------------------------------------
-- Table `auction_platform`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_platform`.`USERS` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Permission_level` INT NOT NULL COMMENT 'Permission level = 1 is admin level permissions (includes seller level permissions)\nPermision level = 2 is seller level permissions (includes buyer level permissions)\nPermission level = 3 is buyer level permissions',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_platform`.`BUYERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_platform`.`BUYERS` (
  `buyer_id` INT NOT NULL,
  `USERS_user_id` INT NOT NULL,
  `buyer_rating` INT NULL,
  `address_line_1` VARCHAR(45) NULL,
  `address_line_2` VARCHAR(45) NULL,
  `address_line_3` VARCHAR(45) NULL,
  `address_city` VARCHAR(45) NULL,
  `address_postcode` VARCHAR(45) NULL,
  INDEX `fk_buyers_users1_idx` (`USERS_user_id` ASC),
  PRIMARY KEY (`buyer_id`),
  CONSTRAINT `fk_buyers_users1`
    FOREIGN KEY (`USERS_user_id`)
    REFERENCES `auction_platform`.`USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_platform`.`SELLERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_platform`.`SELLERS` (
  `seller_id` VARCHAR(45) NOT NULL,
  `USERS_user_id` INT NOT NULL,
  `seller_rating` INT NULL,
  INDEX `fk_sellers_users1_idx` (`USERS_user_id` ASC),
  PRIMARY KEY (`seller_id`),
  CONSTRAINT `fk_sellers_users1`
    FOREIGN KEY (`USERS_user_id`)
    REFERENCES `auction_platform`.`USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_platform`.`LISTED_ITEMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_platform`.`LISTED_ITEMS` (
  `auction_listing_nbr` INT NOT NULL,
  `sellers_seller_id` VARCHAR(45) NOT NULL,
  `item_title` VARCHAR(45) NOT NULL,
  `item_description` VARCHAR(450) NOT NULL,
  `item_start_price` DECIMAL NULL,
  `item_reserve_price` DECIMAL NULL,
  `item_listing_start_time` DATETIME NOT NULL,
  `item_listing_end_time` DATETIME NOT NULL,
  `item_image1` VARCHAR(45) NULL,
  `item_image2` VARCHAR(45) NULL,
  `item_image3` VARCHAR(45) NULL,
  INDEX `fk_listed_auction_items_sellers1_idx` (`sellers_seller_id` ASC),
  PRIMARY KEY (`auction_listing_nbr`),
  CONSTRAINT `fk_listed_auction_items_sellers1`
    FOREIGN KEY (`sellers_seller_id`)
    REFERENCES `auction_platform`.`SELLERS` (`seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_platform`.`BIDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_platform`.`BIDS` (
  `bid_nbr` INT NOT NULL,
  `BUYERS_buyer_id` INT NOT NULL,
  `bid_amount` VARCHAR(45) NULL,
  `bid_time` VARCHAR(45) NULL,
  `LISTED_ITEMS_auction_listing_nbr` INT NOT NULL,
  INDEX `fk_bids_buyers1_idx` (`BUYERS_buyer_id` ASC),
  PRIMARY KEY (`bid_nbr`),
  INDEX `fk_BIDS_LISTED_ITEMS1_idx` (`LISTED_ITEMS_auction_listing_nbr` ASC),
  CONSTRAINT `fk_bids_buyers1`
    FOREIGN KEY (`BUYERS_buyer_id`)
    REFERENCES `auction_platform`.`BUYERS` (`buyer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BIDS_LISTED_ITEMS1`
    FOREIGN KEY (`LISTED_ITEMS_auction_listing_nbr`)
    REFERENCES `auction_platform`.`LISTED_ITEMS` (`auction_listing_nbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_platform`.`ADMINS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_platform`.`ADMINS` (
  `admin_id` VARCHAR(45) NOT NULL,
  `USERS_user_id` INT NOT NULL,
  `BUYERS_buyer_id` INT NOT NULL,
  `SELLERS_seller_id` VARCHAR(45) NOT NULL,
  `BIDS_bid_nbr` INT NOT NULL,
  `LISTED_ITEMS_auction_listing_nbr` INT NOT NULL,
  INDEX `fk_administrators_users_idx` (`USERS_user_id` ASC),
  PRIMARY KEY (`admin_id`),
  INDEX `fk_ADMINS_BUYERS1_idx` (`BUYERS_buyer_id` ASC),
  INDEX `fk_ADMINS_SELLERS1_idx` (`SELLERS_seller_id` ASC),
  INDEX `fk_ADMINS_BIDS1_idx` (`BIDS_bid_nbr` ASC),
  INDEX `fk_ADMINS_LISTED_ITEMS1_idx` (`LISTED_ITEMS_auction_listing_nbr` ASC),
  CONSTRAINT `fk_administrators_users`
    FOREIGN KEY (`USERS_user_id`)
    REFERENCES `auction_platform`.`USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADMINS_BUYERS1`
    FOREIGN KEY (`BUYERS_buyer_id`)
    REFERENCES `auction_platform`.`BUYERS` (`buyer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADMINS_SELLERS1`
    FOREIGN KEY (`SELLERS_seller_id`)
    REFERENCES `auction_platform`.`SELLERS` (`seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADMINS_BIDS1`
    FOREIGN KEY (`BIDS_bid_nbr`)
    REFERENCES `auction_platform`.`BIDS` (`bid_nbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADMINS_LISTED_ITEMS1`
    FOREIGN KEY (`LISTED_ITEMS_auction_listing_nbr`)
    REFERENCES `auction_platform`.`LISTED_ITEMS` (`auction_listing_nbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_platform`.`CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_platform`.`CATEGORIES` (
  `LISTED_ITEMS_auction_listing_nbr` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  INDEX `fk_categories_listed_auction_items1_idx` (`LISTED_ITEMS_auction_listing_nbr` ASC),
  CONSTRAINT `fk_categories_listed_auction_items1`
    FOREIGN KEY (`LISTED_ITEMS_auction_listing_nbr`)
    REFERENCES `auction_platform`.`LISTED_ITEMS` (`auction_listing_nbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_platform`.`WATCHED_ITEMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_platform`.`WATCHED_ITEMS` (
  `BUYERS_buyer_id` INT NOT NULL,
  `LISTED_ITEMS_auction_listing_nbr` INT NOT NULL,
  INDEX `fk_WATCHED_ITEMS_BUYERS1_idx` (`BUYERS_buyer_id` ASC),
  INDEX `fk_WATCHED_ITEMS_LISTED_ITEMS1_idx` (`LISTED_ITEMS_auction_listing_nbr` ASC),
  CONSTRAINT `fk_WATCHED_ITEMS_BUYERS1`
    FOREIGN KEY (`BUYERS_buyer_id`)
    REFERENCES `auction_platform`.`BUYERS` (`buyer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WATCHED_ITEMS_LISTED_ITEMS1`
    FOREIGN KEY (`LISTED_ITEMS_auction_listing_nbr`)
    REFERENCES `auction_platform`.`LISTED_ITEMS` (`auction_listing_nbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_platform`.`RATINGS_AND_FEEDBACK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_platform`.`RATINGS_AND_FEEDBACK` (
  `BUYERS_buyer_id` INT NOT NULL,
  `SELLERS_seller_id` VARCHAR(45) NOT NULL,
  `LISTED_ITEMS_auction_listing_nbr` INT NOT NULL,
  `rating` INT NULL,
  `feedback` VARCHAR(100) NULL,
  INDEX `fk_RATINGS_AND_FEEDBACK_BUYERS1_idx` (`BUYERS_buyer_id` ASC),
  INDEX `fk_RATINGS_AND_FEEDBACK_SELLERS1_idx` (`SELLERS_seller_id` ASC),
  INDEX `fk_RATINGS_AND_FEEDBACK_LISTED_ITEMS1_idx` (`LISTED_ITEMS_auction_listing_nbr` ASC),
  CONSTRAINT `fk_RATINGS_AND_FEEDBACK_BUYERS1`
    FOREIGN KEY (`BUYERS_buyer_id`)
    REFERENCES `auction_platform`.`BUYERS` (`buyer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RATINGS_AND_FEEDBACK_SELLERS1`
    FOREIGN KEY (`SELLERS_seller_id`)
    REFERENCES `auction_platform`.`SELLERS` (`seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RATINGS_AND_FEEDBACK_LISTED_ITEMS1`
    FOREIGN KEY (`LISTED_ITEMS_auction_listing_nbr`)
    REFERENCES `auction_platform`.`LISTED_ITEMS` (`auction_listing_nbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auction_platform`.`ENDED_ITEMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_platform`.`ENDED_ITEMS` (
  `LISTED_ITEMS_auction_listing_nbr` INT NOT NULL,
  `BIDS_bid_nbr` INT NOT NULL,
  `sold_amount` DECIMAL NULL,
  INDEX `fk_ENDED_ITEMS_LISTED_ITEMS1_idx` (`LISTED_ITEMS_auction_listing_nbr` ASC),
  INDEX `fk_ENDED_ITEMS_BIDS1_idx` (`BIDS_bid_nbr` ASC),
  CONSTRAINT `fk_ENDED_ITEMS_LISTED_ITEMS1`
    FOREIGN KEY (`LISTED_ITEMS_auction_listing_nbr`)
    REFERENCES `auction_platform`.`LISTED_ITEMS` (`auction_listing_nbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENDED_ITEMS_BIDS1`
    FOREIGN KEY (`BIDS_bid_nbr`)
    REFERENCES `auction_platform`.`BIDS` (`bid_nbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
